### ISSUE TITLE
how to write log to redis/kafka when spark job run on yarn mode?

### ISSUE THREAD

**Issue by github-liyan** [jfgrim/injectLog4jToRedis#1]
I add this pom.xml in my project and test in IDE IDEA ，log can be write to  redis，But in spark on cluster mode ，ClassNotFoundException

**Comment by jfgrim** [comment]
Hi Liyan,
correct your [redis4AppenderLog4j problem](https://github.com/jfgrim/redis4AppenderLog4j/issues/1) before, run this project. 
This project had been created for test my implementation for redis4AppenderLog4j's project. 
It's destinate for local execution, not really for the cloud configuration.
